# Generated by Django 5.1.2 on 2024-10-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('specification', models.TextField()),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uom', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('vendor_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('l1_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_f', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('freight_vendor_to_idi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freight_idi_to_customer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quoted_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quotation_no', models.CharField(max_length=100)),
                ('quotation_date', models.DateField()),
                ('purchase_order_no', models.CharField(max_length=100)),
                ('purchase_order_date', models.DateField()),
                ('del_target_date', models.DateField()),
                ('actual_delivery_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
