#DataAdd/forms.py

class ProductForm:
    pass


from django import forms
from .models import ProductData

class ProductDataForm(forms.ModelForm):
    class Meta:
        model = ProductData
        fields = '__all__'  # Use all fields in the form


# forms.py

from django import forms
from .models import ProductData

PRODUCT_CHOICES = [
    ("Industrial Muffle furnace", "Industrial Muffle furnace"),
    ("Small Chamber Muffle Furnace", "Small Chamber Muffle Furnace"),
    ("Medium Chamber Muffle Furnace", "Medium Chamber Muffle Furnace"),
    ("Large Chamber Muffle Furnace", "Large Chamber Muffle Furnace"),
    ("Multi-Purpose Muffle Furnace", "Multi-Purpose Muffle Furnace"),
    ("Industrial Customised Oven", "Industrial Customised Oven"),
    ("Industrial Heating Oven", "Industrial Heating Oven"),
    ("Industrial Gas Oven", "Industrial Gas Oven"),
    ("Industrial Drying Ovens", "Industrial Drying Ovens"),
    ("Welding Electrode Drying Oven", "Welding Electrode Drying Oven"),
    ("Powder Coating Batch Ovens", "Powder Coating Batch Ovens"),
    ("Industrial Annealing oven", "Industrial Annealing oven"),
    ("Industrial Sintering oven", "Industrial Sintering oven"),
    ("Industrial Box Oven", "Industrial Box Oven"),
    ("Aluminium Aging Oven", "Aluminium Aging Oven"),
    ("Composite Curing Oven", "Composite Curing Oven"),
    ("Custom Batch Oven", "Custom Batch Oven"),
    ("Drop Bottom Batch Oven", "Drop Bottom Batch Oven"),
    ("Heat Treat Oven", "Heat Treat Oven"),
    ("Pit Batch Oven", "Pit Batch Oven"),
    ("Small Batch Oven", "Small Batch Oven"),
    ("Standard Top Load Oven", "Standard Top Load Oven"),
    ("Air Sealed Overhead Trolley Conveyor Oven", "Air Sealed Overhead Trolley Conveyor Oven"),
    ("Belt Conveyor Oven", "Belt Conveyor Oven"),
    ("Carousel Conveyor Oven", "Carousel Conveyor Oven"),
    ("Chain Conveyor Oven", "Chain Conveyor Oven"),
    ("Custom Conveyor Oven", "Custom Conveyor Oven"),
    ("Indexing Conveyor Oven", "Indexing Conveyor Oven"),
    ("Spindle Chain Edge Conveyor Oven", "Spindle Chain Edge Conveyor Oven"),
    ("Vertical Conveyor Oven", "Vertical Conveyor Oven"),
    ("Trip Cure Oven", "Trip Cure Oven"),
    ("Industrial Walk-In Oven", "Industrial Walk-In Oven"),
    ("Custom Industrial Oven", "Custom Industrial Oven"),
    ("Vacuum Heat Treatment furnace", "Vacuum Heat Treatment furnace"),
    ("Brazing Vacuum Furnace", "Brazing Vacuum Furnace"),
    ("Carburizing Vacuum Furnace", "Carburizing Vacuum Furnace"),
    ("Hardening Vacuum Furnace", "Hardening Vacuum Furnace"),
    ("Sintering Vacuum Furnace", "Sintering Vacuum Furnace"),
    ("Surface Treatments Vacuum Furnace", "Surface Treatments Vacuum Furnace"),
    ("Tempering Vacuum Furnace", "Tempering Vacuum Furnace"),
    ("Pit Type furnace", "Pit Type furnace"),
    ("Cyclone Electric Pit Furnace", "Cyclone Electric Pit Furnace"),
    ("Cyclone Electric Retort Pit Nitriding Furnace", "Cyclone Electric Retort Pit Nitriding Furnace"),
    ("Cyclone Gas-Fired Pit Furnace", "Cyclone Gas-Fired Pit Furnace"),
    ("Cyclone Gas-Fired Retort Pit Nitriding Furnace", "Cyclone Gas-Fired Retort Pit Nitriding Furnace"),
    ("Carburizing Pit Furnace", "Carburizing Pit Furnace"),
    ("Nitriding Pit Furnace", "Nitriding Pit Furnace"),
    ("Tempering Pit Furnace", "Tempering Pit Furnace"),
    ("Rod Overbend Pit Furnace", "Rod Overbend Pit Furnace"),
    ("Pit Furnace Companion Quench Tank", "Pit Furnace Companion Quench Tank"),
    ("Industrial Box furnace", "Industrial Box furnace"),
    ("Cyclone Box Furnace", "Cyclone Box Furnace"),
    ("Gas-Fired Radiant Tube Box Furnace", "Gas-Fired Radiant Tube Box Furnace"),
    ("Investment Cast Burn-Out Box Furnace", "Investment Cast Burn-Out Box Furnace"),
    ("Polymer Burn-Off Box Furnace", "Polymer Burn-Off Box Furnace"),
    ("Rod Overbend Box Furnace", "Rod Overbend Box Furnace"),
    ("Silicon Carbide Element Box Furnace", "Silicon Carbide Element Box Furnace"),
    ("Utility Box Furnace", "Utility Box Furnace"),
    ("Industrial Horizontal Furnace", "Industrial Horizontal Furnace"),
    ("Car Bottom Box Furnace", "Car Bottom Box Furnace"),
    ("Electrical Control Panels", "Electrical Control Panels"),
    ("PLC Control Panel, AC Drive Panel", "PLC Control Panel, AC Drive Panel"),
    ("L.T. PCC Panel, MCC Panel, Mimic Panel", "L.T. PCC Panel, MCC Panel, Mimic Panel"),
    ("Industrial APFC Panel, AMF & DG Panel", "Industrial APFC Panel, AMF & DG Panel"),
    ("Power Distribution Panel", "Power Distribution Panel"),
    ("Starter Panel DOL/Star Delta, Feeder Panel", "Starter Panel DOL/Star Delta, Feeder Panel"),
    ("Industrial Metering Panel (Industrial Energy Meter Panel Board)", "Industrial Metering Panel (Industrial Energy Meter Panel Board)"),
    ("Scada (Supervisory Control and Data Acquisition Control System)", "Scada (Supervisory Control and Data Acquisition Control System)"),
    ("L.T. PCC Panel", "L.T. PCC Panel"),
    ("MCC Control Panel", "MCC Control Panel"),
    ("PLC Control Panel", "PLC Control Panel"),
    ("Star Delta Panel", "Star Delta Panel"),
    ("Industrial AMF Panel", "Industrial AMF Panel"),
    ("AC Drive Panel", "AC Drive Panel"),
    ("Electrical Feeder Panel", "Electrical Feeder Panel"),
    ("Mimic Control Panel", "Mimic Control Panel"),
    ("Electrical APFC Panel", "Electrical APFC Panel"),
    ("Electric Aluminium Melting Furnace", "Electric Aluminium Melting Furnace"),
    ("Electric Aluminium Melting Skelner", "Electric Aluminium Melting Skelner"),
    ("Aluminium Melting Cum Holding furnace", "Aluminium Melting Cum Holding furnace"),
    ("Fix Aluminium Electric LPDC Aluminium Holding furnace", "Fix Aluminium Electric LPDC Aluminium Holding furnace"),
    ("Copper Melting furnace", "Copper Melting furnace"),
    ("Brass Melting furnace", "Brass Melting furnace"),
    ("Induction Gold Melting furnace", "Induction Gold Melting furnace"),
    ("Industrial Crucible furnace", "Industrial Crucible furnace"),
    ("Induction Silver Melting furnace", "Induction Silver Melting furnace"),
    ("Induction Platinum Melting furnace", "Induction Platinum Melting furnace"),
    ("Induction Melting furnace", "Induction Melting furnace"),
    ("Metal Melting furnace", "Metal Melting furnace"),
    ("Non Ferrous Melting furnace", "Non Ferrous Melting furnace"),
    ("Reverberatory Aluminium Melting Furnace", "Reverberatory Aluminium Melting Furnace"),
    ("Aluminium Melting Furnace", "Aluminium Melting Furnace"),
    ("Industrial Front well Furnace", "Industrial Front well Furnace"),
    ("Industrial Side well Furnace", "Industrial Side well Furnace"),
    ("Industrial Stack Melter", "Industrial Stack Melter"),
    ("Dry Hearth Melter", "Dry Hearth Melter"),
    ("Aluminium Holding Furnace", "Aluminium Holding Furnace"),
    ("Aluminium Launder System", "Aluminium Launder System"),
    ("Electric Immersion Holding Furnace", "Electric Immersion Holding Furnace"),
    ("Gas Fired Holding Furnace", "Gas Fired Holding Furnace"),
    ("Gas Fired Stationary Crucible / Pot Melting Furnace", "Gas Fired Stationary Crucible / Pot Melting Furnace"),
    ("Stationary Electric Crucible / Pot Melting Furnace", "Stationary Electric Crucible / Pot Melting Furnace"),
    ("Tilting Electric Crucible / Pot Melting Furnace", "Tilting Electric Crucible / Pot Melting Furnace"),
    ("Gas Fired Immersion Tube Zinc Melting Furnace", "Gas Fired Immersion Tube Zinc Melting Furnace"),
    ("Electric Immersion Holding And Melting Holding Furnace", "Electric Immersion Holding And Melting Holding Furnace"),
    ("Furnace Maintenance Service", "Furnace Maintenance Service"),
    ("Furnace Repair Service", "Furnace Repair Service"),
    ("Refractory Lining Service", "Refractory Lining Service"),
    ("Refractory Application Services", "Refractory Application Services"),
    ("Aluminium furnace Lining Services", "Aluminium furnace Lining Services"),
    ("Forging furnace Lining (Forging furnace Refractory Lining Services)", "Forging furnace Lining (Forging furnace Refractory Lining Services)"),
    ("Aluminium Transfer Ladles", "Aluminium Transfer Ladles"),
    ("Molten Metal Transfer Ladles", "Molten Metal Transfer Ladles"),
    ("Tubothal Radiant Tube Heaters", "Tubothal Radiant Tube Heaters"),
    ("Thermocouple Sensor Bayonet Industrial Thermocouple", "Thermocouple Sensor Bayonet Industrial Thermocouple"),
    ("Multi Point Temperature Indicator", "Multi Point Temperature Indicator"),
    ("Rotating Bayonet RTD Type Thermocouple", "Rotating Bayonet RTD Type Thermocouple"),
    ("Tumblast Shot Blasting Machine", "Tumblast Shot Blasting Machine"),
    ("Shot Blasting Machine", "Shot Blasting Machine"),
    ("Airless Shot Blasting Machine", "Airless Shot Blasting Machine"),
    ("Y-Hanger Type Shot Blasting Machine", "Y-Hanger Type Shot Blasting Machine"),
    ("Hanger Type Shot Blasting Machine", "Hanger Type Shot Blasting Machine"),
    ("Industrial Conveyor Furnace", "Industrial Conveyor Furnace"),
    ("Drop Bottom Batch Oven", "Drop Bottom Batch Oven"),
    ("Rotary Hearth furnace", "Rotary Hearth furnace"),
    ("Gas Fired Chamber Oven", "Gas Fired Chamber Oven"),
    ("Batch Type Oven", "Batch Type Oven"),
    ("Ladle Preheating Furnace", "Ladle Preheating Furnace"),
    ("Zinc Pot Melting Furnace", "Zinc Pot Melting Furnace"),
    ("Car Bottom Furnace", "Car Bottom Furnace"),
    ("Multi-Tube Melting Furnace", "Multi-Tube Melting Furnace"),
    ("Non Ferrous Metal Furnace", "Non Ferrous Metal Furnace"),
    ("Metal Transfer Ladle", "Metal Transfer Ladle"),
    ("Cupola furnace", "Cupola furnace"),
    ("Die Casting Machines", "Die Casting Machines"),
    ("Aluminium Melting furnace", "Aluminium Melting furnace"),
    ("Gas Fired Annealing Oven", "Gas Fired Annealing Oven"),
    ("Resistance Furnace", "Resistance Furnace"),
    ("Tempering Furnace", "Tempering Furnace"),
    ("Induction Melting Furnace", "Induction Melting Furnace"),
    ("Pit Type Induction Furnace", "Pit Type Induction Furnace"),
    ("Induction Smelting Furnace", "Induction Smelting Furnace"),
    ("Induction Holding Furnace", "Induction Holding Furnace"),
    ("Induction Heating Furnace", "Induction Heating Furnace"),
    ("Induction Batch Furnace", "Induction Batch Furnace"),
    ("Vertical Induction Furnace", "Vertical Induction Furnace"),
    ("Induction Crucible Furnace", "Induction Crucible Furnace"),
    ("Tilting Induction Furnace", "Tilting Induction Furnace"),
    ("Foundry Induction Furnace", "Foundry Induction Furnace"),
    ("Induction Melting furnace for Copper", "Induction Melting furnace for Copper"),
    ("Induction Melting furnace for Brass", "Induction Melting furnace for Brass"),
    ("Electromagnetic Furnace", "Electromagnetic Furnace"),
    ("Coreless Induction Melting Furnace", "Coreless Induction Melting Furnace"),
    ("Induction Melting Furnace for Metal", "Induction Melting Furnace for Metal"),
    ("Induction Melting Furnace for Iron", "Induction Melting Furnace for Iron"),
    ("Induction Melting Furnace for Aluminium", "Induction Melting Furnace for Aluminium"),
    ("Induction Melting Furnace for Zink", "Induction Melting Furnace for Zink"),
    ("Induction Furnace for Scrap", "Induction Furnace for Scrap"),
    ("Induction Furnace for Gold", "Induction Furnace for Gold"),
    ("Induction Furnace for Silver", "Induction Furnace for Silver"),
    ("Induction Furnace for Bronze", "Induction Furnace for Bronze"),
    ("Induction Furnace for Brass", "Induction Furnace for Brass"),
    ("Induction Furnace for Copper", "Induction Furnace for Copper"),
    ("Induction Furnace for Stainless Steel", "Induction Furnace for Stainless Steel"),
    ("Induction Furnace for cast iron", "Induction Furnace for cast iron"),
    ("Induction Furnace for soft metal", "Induction Furnace for soft metal"),
]


class ProductForm(forms.ModelForm):
    product_name = forms.ChoiceField(choices=PRODUCT_CHOICES)

    class Meta:
        model = ProductData
        fields = '__all__'

#------------------------------------------------------------------------------

