# Generated by Django 5.1.1 on 2024-09-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=255)),
                ('specification', models.TextField()),
                ('customer_name', models.CharField(max_length=255)),
                ('l1_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gross_cost_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor1_name', models.CharField(max_length=255)),
                ('vendor1_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor2_name', models.CharField(max_length=255)),
                ('vendor2_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor3_name', models.CharField(max_length=255)),
                ('vendor3_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
